name: Wizcat Studios
title: Wizcat Studios
description: Wizcat Studios is a software and game developer company based in Sweden
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: wizcatstudios@gmail.com
# See: https://disqus.com/
disqus_username:
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id:
